# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r2_hIldvlS2iljB8vRyM2Ob4imdUqpA6
"""

!pip install -q openai

import openai

openai.api_key = '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'

import openai

messages = [
    {"role": "system", "content": "You are an informative, responsible ChatBot"}
]

while True:
  message = input("User : ")
  if message:
    messages.append(
        {"role": "system", "content": message},
        )
    chat = openai.ChatCompletion.create(
        model = "gpt-3.5-turbo", messages = messages
    )
    reply = chat.choices[0].message.content
    print(f"ChatGPT: {reply}")
    messages.append({"role": "assistant", "content": "reply"})